name: Build and Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt install -y libmhash-dev libmcrypt-dev libjpeg-dev zlib1g-dev autoconf build-essential
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: Run cracker tests
      run: cd tests/stegseek && ./testCracker.sh && cd ../..
    - name: Create a .deb package
      run: bash package/package
    - name: Save the .deb as a build artifact
      uses: actions/upload-artifact@v2
      with:
        name: stegseek-deb-package
        path: stegseek*.deb
