name: Build and Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt install -y libmhash-dev libmcrypt-dev libjpeg-dev zlib1g-dev autoconf build-essential
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: Run cracker tests
      run: cd tests/stegseek && ./testCracker.sh

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: 'libmhash-devel libmcrypt-devel libjpeg-devel zlib1g-devel autoconf'
    - uses: actions/checkout@v2
    - shell: msys2 {0}
      run:  |
        cd stegseek
        autoreconf -i
        ./configure
        make
