name: Build and Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xmllint
      run: sudo apt install -y libmhash-dev libmcrypt-dev libjpeg-dev zlib1g-dev autoconf build-essential
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
